name: ezcharge
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.2
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  firebase_storage: ^13.0.1
  mobile_scanner: ^7.0.1
  image_picker: ^1.2.0
  file_picker: ^10.3.3
  google_sign_in: ^7.2.0
  intl: ^0.19.0
  google_maps_flutter: ^2.13.1
  location: ^8.0.1
  flutter_polyline_points: ^3.0.1
  provider: ^6.1.5+1
  geolocator: ^14.0.2
  pinput: ^5.0.2
  get: ^4.7.2
  dash_chat_2: ^0.0.21
  chat_gpt_sdk: ^3.1.5
  fl_chart: ^1.1.1
  pdf: ^3.11.3
  printing: ^5.14.2
  google_fonts: ^6.3.1
  carousel_slider: ^5.1.1
  camera: ^0.11.2
  google_mlkit_face_detection: ^0.13.1
  qr_flutter: ^4.1.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/ezcharge_logo.png"
